version: '3'

services:
  spiped-generate-key:
    image: spiped:1.6.1-alpine
    entrypoint: [""]
    command: spiped-generate-key.sh
    volumes:
      - private/spiped-keyfile:/spiped/key:rw
  spiped-decryptor-example:
    image: spiped:1.6.1-alpine
    command: spiped -d -s '[0.0.0.0]:<listening-port>' -t '<service-ip>:<service-port>'
    volumes: 
      - private/spiped-keyfile:/spiped/key:ro
    user: spiped
  spiped-encryptor-example:
    image: spiped:1.6.1-alpine
    command: spiped -e -s '[0.0.0.0]:<service-port>' -t '<decryptor-ip>:<decryptor-port>'
    volumes: 
      - private/spiped-keyfile:/spiped/key:ro
    ports:
      - "<service-port>:<service-port>"
    user: spiped
