version: '3'

services:
  redis-example:
    image: redis:6.2.6-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - private/redis.conf:/usr/local/etc/redis/redis.conf
      - private/redis.db:/usr/local/etc/redis/redis.db
